# Generated by Django 6.0.2 on 2026-03-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cource_alter_student_options_student_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cource',
            new_name='Course',
        ),
    ]
