# Generated by Django 6.0.2 on 2026-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_cource_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Kurs haqida qisqacha'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text='FontAwesome klassi (masalan: fas fa-code)', max_length=50, verbose_name='Belgi (Icon)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Chegirma miqdori'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_type',
            field=models.CharField(choices=[('flex', 'Aniq summa'), ('percent', 'Foizli')], max_length=10, verbose_name='Chegirma turi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Asl narxi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kurs nomi'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('age', models.IntegerField(default=5, verbose_name='Yoshi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='main.course', verbose_name='Kurslari')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
