# Generated by Django 6.0.2 on 2026-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_options_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
        migrations.RemoveField(
            model_name='students',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_active',
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=917524233, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.DateField(blank=True, null=True, verbose_name='Username'),
        ),
    ]
