# Generated by Django 6.0.2 on 2026-04-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_students_age_remove_students_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(default='Abdulloh Akramov', max_length=255, verbose_name='F.I.SH'),
        ),
    ]
